# Main clock
create_clock -name CLK_200M -period 5.000 [get_ports CLK_200M_P]
set_property PACKAGE_PIN AC18 [get_ports CLK_200M_P]
set_property PACKAGE_PIN AD18 [get_ports CLK_200M_N]
set_property IOSTANDARD LVDS [get_ports CLK_200M_P]
set_property IOSTANDARD LVDS [get_ports CLK_200M_N]

# VGA
set_property PACKAGE_PIN N21 [get_ports {vga_red[0]}]
set_property PACKAGE_PIN N22 [get_ports {vga_red[1]}]
set_property PACKAGE_PIN R21 [get_ports {vga_red[2]}]
set_property PACKAGE_PIN P21 [get_ports {vga_red[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_red[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_red[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_red[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_red[0]}]
set_property PACKAGE_PIN R22 [get_ports {vga_green[0]}]
set_property PACKAGE_PIN R23 [get_ports {vga_green[1]}]
set_property PACKAGE_PIN T24 [get_ports {vga_green[2]}]
set_property PACKAGE_PIN T25 [get_ports {vga_green[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_green[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_green[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_green[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_green[0]}]
set_property PACKAGE_PIN T20 [get_ports {vga_blue[0]}]
set_property PACKAGE_PIN R20 [get_ports {vga_blue[1]}]
set_property PACKAGE_PIN T22 [get_ports {vga_blue[2]}]
set_property PACKAGE_PIN T23 [get_ports {vga_blue[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_blue[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_blue[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_blue[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_blue[0]}]
set_property PACKAGE_PIN M22 [get_ports vga_hs]
set_property PACKAGE_PIN M21 [get_ports vga_vs]
set_property IOSTANDARD LVCMOS33 [get_ports vga_hs]
set_property IOSTANDARD LVCMOS33 [get_ports vga_vs]